spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
      - id: api-1
        uri: lb://WELCOMEMSG
        predicates: 
          - Path=/welcome
      - id: api-2
        uri: lb://GREATAPI
        predicates: 
          - Path=/greet
  main:
    web-application-type: reactive        
server:
  port: 3333
