spring:
  application:
    name: welcome
  config:
    import: optional:configserver:http://localhost:9093  
server:
  port: 8081
  #for Refresh 
management:
  endpoints:
    web:
      exposure:
        include:
        - refresh  