management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9091
spring:
  application:
    name: GreatAPI
  boot:
    admin:
      client:
        url: http://localhost:1111
